sudo: false
language: ruby
rvm: 2.5.6
cache: bundler
addons:
  postgresql: "9.6"
before_script:
  - bundle exec rake db:create
  - bundle exec rake db:schema:load db:test:prepare
script:
  - bundle exec rubocop
  - bundle exec rspec
